FeedBack360Project/Controllers/FeedbackSchController.cs
using DLFeedBack360.Infrastructure.Abstract;
using DLFeedBack360.Infrastructure.Repository;
using DLFeedBack360.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace FeedBack360Project.Controllers
{
    [Authorize]
    public class FeedbackSchController : Controller
    {
        IUserManagementRepo _umRepo = new UserManagementRepo();

        [Authorize(Roles = "HR,Admin")]
        [HttpGet]
        public IActionResult ScheduleFB()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            FeedbackSchDtlViewModel FeedbackSchDtl = new FeedbackSchDtlViewModel();
            FeedbackSchDtl.getUserIDDetail = _umRepo.GetUserID();
            FeedbackSchDtl.getFeedbackCatagoryDetail = _umRepo.GetFeedbackcatagory();
            FeedbackSchDtl.getProviderUserIDDetail = _umRepo.GetProviderUserID();

            return View(FeedbackSchDtl);
        }

        [Authorize(Roles = "HR,Admin")]
        [HttpPost]
        public IActionResult ScheduleFB(FeedbackSchDtlViewModel fbsdvm)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            string msg = _umRepo.SetFeedbackProviderList(fbsdvm);
            ViewBag.Result = msg;
            if (msg == "Success")
            {
                FeedbackSchDtlViewModel FeedbackSchDtl = new FeedbackSchDtlViewModel();
                FeedbackSchDtl.getUserIDDetail = _umRepo.GetUserID();
                FeedbackSchDtl.getFeedbackCatagoryDetail = _umRepo.GetFeedbackcatagory();
                FeedbackSchDtl.getProviderUserIDDetail = _umRepo.GetProviderUserID();
                return View(FeedbackSchDtl);
            }
            return View(fbsdvm);
        }

        [Authorize(Roles = "HR,Admin")]
        [HttpPost]
        public JsonResult GetFBProvider(string userId, string categoryid)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            List<System.Web.Mvc.SelectListItem> FBProviderList = new List<System.Web.Mvc.SelectListItem>();
            FBProviderList = _umRepo.GetFeedbackProviderList(categoryid, userId);

            return Json(FBProviderList);
        }
    }
}

FeedBack360Project/Controllers/ProvideFeedbackController.cs
using DLFeedBack360.Infrastructure.Abstract;
using DLFeedBack360.Infrastructure.Repository;
using DLFeedBack360.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace FeedBack360Project.Controllers
{
    [Authorize]
    public class ProvideFeedbackController : Controller
    {
        IProvideFeedbackRepo _Repofb = new ProvideFeedbackRepo();

        [AllowAnonymous]
        [HttpGet]
        public IActionResult CandidateList()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            List<CandidateListViewModel> candidateList = _Repofb.GetCandidateList(_Repofb.getUserIDtoID(ViewBag.MyUserID));
            return View(candidateList);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult ProvidingFeedback(string userId)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            HttpContext.Session.SetString("CandidateUserName", userId);
            FeedbackProvidingViewModel Fbpvm = _Repofb.getFeedbackQuestion();
            return View(Fbpvm);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ProvidingFeedback(FeedbackProvidingViewModel model)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            ViewBag.ToUserID = HttpContext.Session.GetString("CandidateUserName");
            string result = _Repofb.SetFeedbackRatings(model, _Repofb.getUserIDtoID(ViewBag.ToUserID), _Repofb.getUserIDtoID(ViewBag.MyUserID));
            FeedbackProvidingViewModel Fbpvm = _Repofb.getFeedbackQuestion();
            if (result == "Success")
            {
                ViewBag.Message = "Rating submitted successfully";
                return View(Fbpvm);
            }
            else
            {
                ViewBag.Message = result;
                return View(Fbpvm);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult FeedbackResult()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            List<FeedbackResultViewModel> lst = _Repofb.GetFeedbackResult();
            return View(lst);
        }
    }
}

FeedBack360Project/Controllers/UserManagementController.cs
using DLFeedBack360.Infrastructure.Abstract;
using DLFeedBack360.Infrastructure.Repository;
using DLFeedBack360.ViewModel;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using ULFeedBack360;
using Microsoft.AspNetCore.Authorization;


namespace FeedBack360Project.Controllers
{
    [Authorize]
    public class UserManagementController : Controller
    {
        IUserManagementRepo _umRepo = new UserManagementRepo();

        public IActionResult Home()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            FeedbackUtility feedbackUtility = FeedbackUtility.getInstant();
            feedbackUtility.SendEmail("haneesha0809@gmail.com", "pinjarihaneesha200@gmail.com", "Test Mail", "Hello All, This is test mail");
            return View();
        }

        //Login Code

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Login(LoginViewModel loginView)
        {        
            if (ModelState.IsValid)
            {
                string result = _umRepo.UserLogin(loginView);
                if (result == "Success")
                {
                    HttpContext.Session.SetString("CurrentUser", loginView.UserID.ToString());
                    HttpContext.Session.SetString("CurrentUserRole", _umRepo.GetRole(loginView.UserID.ToString()));
                    ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
                    ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");

                    //Authorization Code Start...............
                    string[] userRoles = new string[] { ViewBag.MyRole };

                    var claims = new List<Claim>();
                    claims.Add(new Claim("username", ViewBag.MyUserID));   // u001
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, ViewBag.MyUserID));      // 1111
                    foreach (var eachRole in userRoles)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, eachRole));
                    }

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                    HttpContext.SignInAsync(claimsPrincipal);

                    //Authorization Code End...............

                   // return RedirectToAction("Registration");
                }
                else
                {
                    ViewBag.LoginStatus = "Login failed, please check User ID and Password";
                    return View();
                }
            }
            return Registration();
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }


        //Registration Code
        [Authorize(Roles = "HR")]
        [HttpGet]
        public IActionResult Registration()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            UserDetailViewModel userDetail = new UserDetailViewModel();
            userDetail.CountryDetail = _umRepo.GetCountries();
            userDetail.LanguageDetail = _umRepo.GetLanguages();
            userDetail.RoleDetail = _umRepo.GetRoles();
            return View("Registration", userDetail);
        }

        //[Authorize(Roles = "HR")]
        [HttpPost] 
        public IActionResult Registration(UserDetailViewModel userDetailView)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            string result = _umRepo.SetRegistration(userDetailView);
            UserDetailViewModel userDetail = new UserDetailViewModel();
            userDetail.CountryDetail = _umRepo.GetCountries();
            userDetail.LanguageDetail = _umRepo.GetLanguages();
            userDetail.RoleDetail = _umRepo.GetRoles();

            if (result == "Success")
            {
                //return RedirectToAction("Home");
                ViewBag.RegistrationStatus = "User registered successfully";
                return View(userDetail);
            }
            else
            {
                ViewBag.RegistrationStatus = "User registration failed!";
                return View(userDetail);
            }
        }
           



        //Change Password Code
        [AllowAnonymous]
        [HttpGet]
        public IActionResult ChangePassword()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordViewModel changePasswordView)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            string result = _umRepo.UpdatePassword(changePasswordView);
            if (result == "Success")
            {
                ViewBag.ChangePasswordStatus = "Password  changed successfully";
                //return RedirectToAction("Home");
                return View();
            }
            else
            {
                ViewBag.ChangePasswordStatus = "Password not changed, Please check!";
                return View();
            }

        }


        //Forget Password Code
        [AllowAnonymous]
        [HttpGet]
        public IActionResult ForgotPassword()
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ForgotPassword(ForgotPasswordViewModel forgotPasswordView, string btn)
        {
            ViewBag.MyUserID = HttpContext.Session.GetString("CurrentUser");
            ViewBag.MyRole = HttpContext.Session.GetString("CurrentUserRole");
            if (btn == "Send OTP")
            {
                string otp = _umRepo.SendOPT(forgotPasswordView.UserID.ToString());
                HttpContext.Session.SetString("MyOTP", otp.ToString());
                string str2 = HttpContext.Session.GetString("MyOTP");
            }
            else if (btn == "submit")
            {
                string str1 = HttpContext.Session.GetString("MyOTP");
                if (forgotPasswordView.PassCode == str1)
                {
                    string result = _umRepo.UserForgotPassword(forgotPasswordView);
                    ViewBag.Result = "Your password reset successfully";
                }
            }

            return View();
        }

    }
}

FeedBack360Project/Views/MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Feedback360.styles.css" asp-append-version="true" />
</head>
<body>
    <div>
        <h5 style="color:blue">
            @{
                @ViewBag.MyUserID
            }
        </h5>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="Home">Home |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProvideFeedback" asp-action="CandidateList">Candidate List |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="ChangePassword">Change Password |</a>
                        </li>

                        @if (ViewBag.MyRole == "HR" || ViewBag.MyRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FeedbackSch" asp-action="ScheduleFB">FeedbackScheduling |</a>
                            </li>
                        }
                        @if (ViewBag.MyRole == "HR")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="Registration">User Registration |</a>
                            </li>
                        }

                        @if (ViewBag.MyRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProvideFeedback" asp-action="FeedbackResult">Providing Result |</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserManagement" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Feedback360 - <a asp-area="" asp-controller="UserManagement" asp-action="Home">Home</a>
        </div>
    </footer>
</body>
</html>